@isTest
public class rsp_BatchTargetDataCorrectionTest 
{

    
    @isTest
    static void rsp_BatchTargetDataCorrection_Test()
    {
        rsp_BatchTargetDataCorrection.dummymethod();
    }
    
    @isTest
    static void rsp_AchievementDataCorrection_Test()
    {
        rsp_AchievementDataCorrection.dummymethod();
    }
    
    @isTest
    static void rsp_OpportunityDataCorrection_Test()
    {
        rsp_BatchDataCorrection.dummymethod();
    }
    
    @isTest
    static void rsp_BatchTargetShareWithBVH_Test()
    {
        rsp_BatchTargetShareWithBVH.dummymethod();
    }
    
    
}