/* ------------------------------------------------------------------------------------------------
    @author :- Rahul Gupta 
    @Company :- Saasfocus
    @description :- This class is responsible to generate the Response for Role Hierachy 
    @Created Date: 02-Aug-2018
    @Version 1.0 
-------------------------------------------------------------------------------------------------*/


global  class Rsp_RoleResponseHandler {
    
    // Declaring all the attributes used to create the Response 
    //public List<sObject> Data {get;set;}
    //public String status {get; set;}
    //public String message {get;set;}
    //public String errorCode {get; set;}
    public String roleId{get;set;}
    public String roleName{get;set;}
    public String parentRoleId{get;set;}
    public String currentUserEmail{get;set;}
    
   
    
       
}