public class testCommented {
    /*public QuoteJSON2Apex obj{set;get;}
    public QuoteJSON2Apex.header objheader{set;get;}
    public List<QuoteJSON2Apex.detail> lstDetail{set;get;}
    public String getInv() {
        return null;
    }

    public string jsonstr{set;get;}
    public string jsonstrvalue{set;get;}
        
    public test (){
    Quote q = [select id, rsp_Json_Payload__c from Quote where id = '0Q05D0000000Y9N' limit 1];
    jsonstr  = q.rsp_Json_Payload__c;  
    List<QuoteJSON2Apex> JSONlst = new List<QuoteJSON2Apex>();
    obj= QuoteJSON2Apex.parse(jsonstr);
    objheader = obj.header;
    system.debug('agrno==>'+objheader.agrno);
    lstDetail = obj.detail;   
    //Parse the JSON String 
    //List<Quote> lstQuote
    
 }*/
 }